const FEATURES = {
  DISPLAY_SOCIAL_MEDIA: false,
  DISPLAY_MEMBERS_SOCIAL_MEDIA: false,
  DISPLAY_MEMBERS_SECTION: false,
  DISPLAY_TESTIMONIAL_SECTION: false,
  DISPLAY_CHOOSE_SECTION_FOOTER: false
};

export default FEATURES;
